layout_spectrum: 0.05191376433896455
typography_spectrum: 0.3957549617625773
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.41186203830875456
  lightness: 0.7639416609890759
  rhythmicContrast: 0.17088589072227478
  saturation: 0.794174863724038
opengraph: {}
analytics: {}
author:
  name: Rod Clark
  email: 157@mistral.co.uk
  url: rodclark.org
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bb32eec7-a2db-4823-9d0a-7d29a08c2d2d.jpg
name: RodClark
cta: {}
navigation:
  - name: 'My book: design philosophy'
    url: 'http://www.soyouthinkyouknowaboutdesign.com'
    type: external
  - name: Design Work
    url: 'http://rodclark.org'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/68c142ef-d62a-448f-b7ef-9532ce685993.jpg
title: '6812'
purpose: {}
