typography_spectrum: 0.4488952495906102
color:
  brandColors:
    - '#A8B8C0'
    - '#0098A8'
    - '#687878'
    - '#00B0C0'
    - '#A0D8F0'
  brandStrength: 0.955019
  lightness: 0.834018
  rhythmicContrast: 0.983195
  saturation: 0.704
opengraph: {}
layout_spectrum: 0.05191376433896455
analytics: {}
name: RodClark
cta: {}
title: soyouthinkyouknowaboutdesign
purpose: {}
