typography_spectrum: 0.4488952495906102
color:
  brandColors:
    - '#A8B8C0'
    - '#0098A8'
    - '#687878'
    - '#00B0C0'
    - '#A0D8F0'
  brandStrength: 0.955019
  lightness: 0.834018
  rhythmicContrast: 0.983195
  saturation: 0.704
opengraph: {}
layout_spectrum: 0.05191376433896455
analytics: {}
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bb32eec7-a2db-4823-9d0a-7d29a08c2d2d.jpg
name: RodClark
cta: {}
navigation:
  - name: design philosophy book
    url: 'http://www.soyouthinkyouknowaboutdesign.com'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/68c142ef-d62a-448f-b7ef-9532ce685993.jpg
title: soyouthinkyouknowaboutdesign
purpose: {}
