analytics: {}
color:
  brandColors:
    - '#C0C8C0'
    - '#000000'
    - '#808080'
    - '#000000'
    - '#000000'
  brandStrength: 0.955019
  lightness: 0.834018
  rhythmicContrast: 0.983195
  saturation: 0.704
cta: {}
layout_spectrum: 0.527027
name: RodClark
opengraph: {}
purpose: {}
typography_spectrum: 0.842905
